// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/device.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	DeviceType    string                 `protobuf:"bytes,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_proto_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ReserveRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_proto_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReserveResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{2}
}

func (x *ReleaseRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_proto_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{4}
}

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	ReservedBy    string                 `protobuf:"bytes,2,opt,name=reserved_by,json=reservedBy,proto3" json:"reserved_by,omitempty"`
	Available     bool                   `protobuf:"varint,3,opt,name=available,proto3" json:"available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_proto_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceStatus) GetReservedBy() string {
	if x != nil {
		return x.ReservedBy
	}
	return ""
}

func (x *DeviceStatus) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_proto_device_proto protoreflect.FileDescriptor

const file_proto_device_proto_rawDesc = "" +
	"\n" +
	"\x12proto/device.proto\x12\x0edevicefleet.v1\"E\n" +
	"\x0eReserveRequest\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\tR\n" +
	"deviceType\"F\n" +
	"\x0fReserveResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"-\n" +
	"\x0eReleaseRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\")\n" +
	"\x0fReleaseResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x0e\n" +
	"\fWatchRequest\"j\n" +
	"\fDeviceStatus\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vreserved_by\x18\x02 \x01(\tR\n" +
	"reservedBy\x12\x1c\n" +
	"\tavailable\x18\x03 \x01(\bR\tavailable2\x81\x02\n" +
	"\rDeviceService\x12P\n" +
	"\rReserveDevice\x12\x1e.devicefleet.v1.ReserveRequest\x1a\x1f.devicefleet.v1.ReserveResponse\x12P\n" +
	"\rReleaseDevice\x12\x1e.devicefleet.v1.ReleaseRequest\x1a\x1f.devicefleet.v1.ReleaseResponse\x12L\n" +
	"\fWatchDevices\x12\x1c.devicefleet.v1.WatchRequest\x1a\x1c.devicefleet.v1.DeviceStatus0\x01B=Z;github.com/gitRasheed/FleetRPC/internal/service/proto;protob\x06proto3"

var (
	file_proto_device_proto_rawDescOnce sync.Once
	file_proto_device_proto_rawDescData []byte
)

func file_proto_device_proto_rawDescGZIP() []byte {
	file_proto_device_proto_rawDescOnce.Do(func() {
		file_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_device_proto_rawDesc), len(file_proto_device_proto_rawDesc)))
	})
	return file_proto_device_proto_rawDescData
}

var file_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_device_proto_goTypes = []any{
	(*ReserveRequest)(nil),  // 0: devicefleet.v1.ReserveRequest
	(*ReserveResponse)(nil), // 1: devicefleet.v1.ReserveResponse
	(*ReleaseRequest)(nil),  // 2: devicefleet.v1.ReleaseRequest
	(*ReleaseResponse)(nil), // 3: devicefleet.v1.ReleaseResponse
	(*WatchRequest)(nil),    // 4: devicefleet.v1.WatchRequest
	(*DeviceStatus)(nil),    // 5: devicefleet.v1.DeviceStatus
}
var file_proto_device_proto_depIdxs = []int32{
	0, // 0: devicefleet.v1.DeviceService.ReserveDevice:input_type -> devicefleet.v1.ReserveRequest
	2, // 1: devicefleet.v1.DeviceService.ReleaseDevice:input_type -> devicefleet.v1.ReleaseRequest
	4, // 2: devicefleet.v1.DeviceService.WatchDevices:input_type -> devicefleet.v1.WatchRequest
	1, // 3: devicefleet.v1.DeviceService.ReserveDevice:output_type -> devicefleet.v1.ReserveResponse
	3, // 4: devicefleet.v1.DeviceService.ReleaseDevice:output_type -> devicefleet.v1.ReleaseResponse
	5, // 5: devicefleet.v1.DeviceService.WatchDevices:output_type -> devicefleet.v1.DeviceStatus
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_device_proto_init() }
func file_proto_device_proto_init() {
	if File_proto_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_device_proto_rawDesc), len(file_proto_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_proto_goTypes,
		DependencyIndexes: file_proto_device_proto_depIdxs,
		MessageInfos:      file_proto_device_proto_msgTypes,
	}.Build()
	File_proto_device_proto = out.File
	file_proto_device_proto_goTypes = nil
	file_proto_device_proto_depIdxs = nil
}
