// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/device.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "github.com/gitRasheed/FleetRPC/internal/service/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DeviceServiceName is the fully-qualified name of the DeviceService service.
	DeviceServiceName = "devicefleet.v1.DeviceService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DeviceServiceReserveDeviceProcedure is the fully-qualified name of the DeviceService's
	// ReserveDevice RPC.
	DeviceServiceReserveDeviceProcedure = "/devicefleet.v1.DeviceService/ReserveDevice"
	// DeviceServiceReleaseDeviceProcedure is the fully-qualified name of the DeviceService's
	// ReleaseDevice RPC.
	DeviceServiceReleaseDeviceProcedure = "/devicefleet.v1.DeviceService/ReleaseDevice"
	// DeviceServiceWatchDevicesProcedure is the fully-qualified name of the DeviceService's
	// WatchDevices RPC.
	DeviceServiceWatchDevicesProcedure = "/devicefleet.v1.DeviceService/WatchDevices"
)

// DeviceServiceClient is a client for the devicefleet.v1.DeviceService service.
type DeviceServiceClient interface {
	ReserveDevice(context.Context, *connect.Request[proto.ReserveRequest]) (*connect.Response[proto.ReserveResponse], error)
	ReleaseDevice(context.Context, *connect.Request[proto.ReleaseRequest]) (*connect.Response[proto.ReleaseResponse], error)
	WatchDevices(context.Context, *connect.Request[proto.WatchRequest]) (*connect.ServerStreamForClient[proto.DeviceStatus], error)
}

// NewDeviceServiceClient constructs a client for the devicefleet.v1.DeviceService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDeviceServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DeviceServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	deviceServiceMethods := proto.File_proto_device_proto.Services().ByName("DeviceService").Methods()
	return &deviceServiceClient{
		reserveDevice: connect.NewClient[proto.ReserveRequest, proto.ReserveResponse](
			httpClient,
			baseURL+DeviceServiceReserveDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ReserveDevice")),
			connect.WithClientOptions(opts...),
		),
		releaseDevice: connect.NewClient[proto.ReleaseRequest, proto.ReleaseResponse](
			httpClient,
			baseURL+DeviceServiceReleaseDeviceProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("ReleaseDevice")),
			connect.WithClientOptions(opts...),
		),
		watchDevices: connect.NewClient[proto.WatchRequest, proto.DeviceStatus](
			httpClient,
			baseURL+DeviceServiceWatchDevicesProcedure,
			connect.WithSchema(deviceServiceMethods.ByName("WatchDevices")),
			connect.WithClientOptions(opts...),
		),
	}
}

// deviceServiceClient implements DeviceServiceClient.
type deviceServiceClient struct {
	reserveDevice *connect.Client[proto.ReserveRequest, proto.ReserveResponse]
	releaseDevice *connect.Client[proto.ReleaseRequest, proto.ReleaseResponse]
	watchDevices  *connect.Client[proto.WatchRequest, proto.DeviceStatus]
}

// ReserveDevice calls devicefleet.v1.DeviceService.ReserveDevice.
func (c *deviceServiceClient) ReserveDevice(ctx context.Context, req *connect.Request[proto.ReserveRequest]) (*connect.Response[proto.ReserveResponse], error) {
	return c.reserveDevice.CallUnary(ctx, req)
}

// ReleaseDevice calls devicefleet.v1.DeviceService.ReleaseDevice.
func (c *deviceServiceClient) ReleaseDevice(ctx context.Context, req *connect.Request[proto.ReleaseRequest]) (*connect.Response[proto.ReleaseResponse], error) {
	return c.releaseDevice.CallUnary(ctx, req)
}

// WatchDevices calls devicefleet.v1.DeviceService.WatchDevices.
func (c *deviceServiceClient) WatchDevices(ctx context.Context, req *connect.Request[proto.WatchRequest]) (*connect.ServerStreamForClient[proto.DeviceStatus], error) {
	return c.watchDevices.CallServerStream(ctx, req)
}

// DeviceServiceHandler is an implementation of the devicefleet.v1.DeviceService service.
type DeviceServiceHandler interface {
	ReserveDevice(context.Context, *connect.Request[proto.ReserveRequest]) (*connect.Response[proto.ReserveResponse], error)
	ReleaseDevice(context.Context, *connect.Request[proto.ReleaseRequest]) (*connect.Response[proto.ReleaseResponse], error)
	WatchDevices(context.Context, *connect.Request[proto.WatchRequest], *connect.ServerStream[proto.DeviceStatus]) error
}

// NewDeviceServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDeviceServiceHandler(svc DeviceServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	deviceServiceMethods := proto.File_proto_device_proto.Services().ByName("DeviceService").Methods()
	deviceServiceReserveDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceReserveDeviceProcedure,
		svc.ReserveDevice,
		connect.WithSchema(deviceServiceMethods.ByName("ReserveDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceReleaseDeviceHandler := connect.NewUnaryHandler(
		DeviceServiceReleaseDeviceProcedure,
		svc.ReleaseDevice,
		connect.WithSchema(deviceServiceMethods.ByName("ReleaseDevice")),
		connect.WithHandlerOptions(opts...),
	)
	deviceServiceWatchDevicesHandler := connect.NewServerStreamHandler(
		DeviceServiceWatchDevicesProcedure,
		svc.WatchDevices,
		connect.WithSchema(deviceServiceMethods.ByName("WatchDevices")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devicefleet.v1.DeviceService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DeviceServiceReserveDeviceProcedure:
			deviceServiceReserveDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceReleaseDeviceProcedure:
			deviceServiceReleaseDeviceHandler.ServeHTTP(w, r)
		case DeviceServiceWatchDevicesProcedure:
			deviceServiceWatchDevicesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDeviceServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDeviceServiceHandler struct{}

func (UnimplementedDeviceServiceHandler) ReserveDevice(context.Context, *connect.Request[proto.ReserveRequest]) (*connect.Response[proto.ReserveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devicefleet.v1.DeviceService.ReserveDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) ReleaseDevice(context.Context, *connect.Request[proto.ReleaseRequest]) (*connect.Response[proto.ReleaseResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devicefleet.v1.DeviceService.ReleaseDevice is not implemented"))
}

func (UnimplementedDeviceServiceHandler) WatchDevices(context.Context, *connect.Request[proto.WatchRequest], *connect.ServerStream[proto.DeviceStatus]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("devicefleet.v1.DeviceService.WatchDevices is not implemented"))
}
